### ISSUE TITLE
How this works

### ISSUE THREAD

**Issue by prashanthbv12** [danhellem/azure-devops-work-items-webhook-sample#11]
Please help me to understand how this works.  I have loaded this webhook sample in IIS(as website) and changed the appsettings.jason file according to my environment details. I have created a webhook in azure devops as well. Now please help me to understand how will I get the request from Azure devops and how to post response back. 
I am new to this and learning more about API's

**Comment by prashanthbv12** [comment]
What will be the endpoint url for this ?

**Comment by danhellem** [comment]
1. First you publish the sample to a public endpoint 
2. then you create a web hook in Azure DevOps for when a work item is created. Send that request to the endpoint above
3. make sure you have a org name and personal access token configured in the json configuration of the project

When the work item is created, it will send the request to the endpoint. The endpoint will take it and assign the work item to the person who created it and add a tag (hardcoded right now).

Let me know if you still have issues
